### ISSUE TITLE
Thanks ... can you add a license?

### ISSUE THREAD

**Issue by tdunning** [mycr0ft/upython_si5351#1]
This is very useful, but would there be a chance to add a license file to this repo with copyright headers in the code itself?

MIT, BSD, Apache would all be good choices for license language.

**Comment by mycr0ft** [comment]
the original code was BSD licensed by LadyAda and I am a fanboy and continuing the BSD license. committed a LICENSE file with 3-clause BSD license.

**Comment by tdunning** [comment]
Dang!

I was just about to send you a pull request after thinking all night about being one of THOSE people who suggest but don't contribute. Well done!

(I am a fanboy of her work as well)
