### ISSUE TITLE
i2c.start() doesn't work on RP2

### ISSUE THREAD

**Issue by tdunning** [mycr0ft/upython_si5351#2]
Micropython doesn't support the `start` and `stop` methods for hardware based I2C implementations such as on the RP2040.

I have confirmed that your code works fine with lines 108 and 112 commented out on the Raspberry Pico W.

More info about this from [here](https://forums.raspberrypi.com/viewtopic.php?t=303613) and [here](https://github.com/micropython/micropython/issues/6856)

**Comment by tdunning** [comment]
My mashup of your code and the CircuitPython code [is here](https://github.com/tdunning/SI5351).

**Comment by tdunning** [comment]
See #3 for changes to close this

**Comment by mycr0ft** [comment]
Removed start and stop in merge with tdunning's version.
